# In backend/integrations.py

# ... (Keep imports and helpers) ...

def fetch_venmo_payments():
    # ... (Keep setup code) ...
                        # ... match logic ...
                        if match:
                            # PASS 'Venmo' AS THE LAST ARGUMENT
                            process_payment(users, match.group(1).strip(), match.group(2), msg["Date"], 'Venmo')
                            payment_count += 1
    # ... (Keep save logic) ...
    return payment_count

def fetch_paypal_payments():
    # ... (Keep setup code) ...
                        # ... match logic ...
                        if match:
                             # PASS 'PayPal' AS THE LAST ARGUMENT
                            process_payment(users, match.group(1).strip(), match.group(2), msg["Date"], 'PayPal')
                            payment_count += 1
    # ... (Keep save logic) ...
    return payment_count

def fetch_zelle_payments():
    # ... (Keep setup code) ...
                        # ... match logic ...
                        if match:
                             # PASS 'Zelle' AS THE LAST ARGUMENT
                            process_payment(users, match.group(2).strip(), match.group(1), msg["Date"], 'Zelle')
                            payment_count += 1
    # ... (Keep save logic) ...
    return payment_count